### ISSUE TITLE
ECHO to VAHydro Mapping

### ISSUE THREAD

**Issue by jdkleiner** [mccartma/USGS_Consumptive_Use#11]
[MAPPING DIAGRAMS FOR REFERENCE](https://github.com/connorb5/USGS_Consumptive_Use/wiki/ECHO----VAHydro-Mapping)

### dH Adminreg Feature Mapping:
bundle | admincode | description | name | ftype | fstatus | startdate | enddate | permit_id | dh_link_admin_reg_issuer
--- | --- | --- | --- | --- | --- | --- | --- | --- | --- 
permit | VA0002585 | National Pollutant Discharge Elimination System (NPDES) Permit | FCWA - LORTON WATER TREATMENT PLANT | npdes | active | 6/28/2012 | 6/27/2017 | VA0002585 | epa  

### Permit date Mapping:
ECHO | VAHydro
--- | ---
CWPEffectiveDate | startdate
ExpDate | enddate

### Permit fstatus Mapping:
ECHO (Status) | VAHydro (fstatus)
--- | ---
Effective | active
Terminated | revoked
Compliance Tracking Off | active
Admin Continued | active
Expired | expired
Effective; Compliance Tracking Partially Off | active
Terminated; Compliance Tracking Off | revoked
Not Needed | unknown
NA | unknown

_Let me know if any other ECHO statuses crop up!_

<br/><br/>

### Facility dH Feature Mapping:
bundle | name | ftype | hydrocode | fstatus | wkt_geom | address1 | city | dh_link_admin_location
--- | --- | --- | --- | --- | --- | --- | --- | ---
facility | FCWA - LORTON WATER TREATMENT PLANT | wwtp |  echo_VA0002585 | active | POINT (-77.256377 38.693388) | 9800 OX RD | LORTON | VA0002585

<br/><br/>

### Facility dH Property Mapping:
1. **Last date permit was inspected on-site**

hydrocode | varkey | propname | propvalue | proptext | propcode | startdate | enddate
--- | ---  | ---  | --- | ---  | --- | ---  | --- 
echo_VA0002585 | last_inspect | last_inspect |  |  |  | 6/28/2017 | 

2. **Logical combined sewer system value**

hydrocode | varkey | propname | propvalue | proptext | propcode | startdate | enddate
--- | ---  | ---  | --- | ---  | --- | ---  | --- 
echo_VA0002585 | css | css |  |  | Yes |  | 

3. **Number of upstream outfalls**

hydrocode | varkey | propname | propvalue | proptext | propcode | startdate | enddate
--- | ---  | ---  | --- | ---  | --- | ---  | --- 
echo_VA0002585 | cwp_cso_outfalls | cwp_cso_outfalls | 42 |  |  |  | 

4. **Receiving waterbody USGS name**

hydrocode | varkey | propname | propvalue | proptext | propcode | startdate | enddate
--- | ---  | ---  | --- | ---  | --- | ---  | --- 
echo_VA0002585 | wb_gnis_name | wb_gnis_name |  |  | James River |  | 

5. **USGS reach code**

hydrocode | varkey | propname | propvalue | proptext | propcode | startdate | enddate
--- | ---  | ---  | --- | ---  | --- | ---  | --- 
echo_VA0002585 | reachcode_rad | reachcode_rad |  |  | 02080203000393 |  | 

6. **Stressors that are causing impairment**

hydrocode | varkey | propname | propvalue | proptext | propcode | startdate | enddate
--- | ---  | ---  | --- | ---  | --- | ---  | --- 
echo_VA0002585 | impair_cause | impair_cause |  | PATHOGENS |  |  | 

<br/><br/>

### Outfall dH Timeseries Mapping:
1. **Discharge - Monthly Average Flow**

hydrocode | varkey | tsvalue | tstime | tsendtime | tscode
--- | ---  | ---  | --- | ---  | ---
echo_VA0002585008 | dmr_mon_mgd | 134 | 9/1/2015 | 9/30/2015 |  1

### Timeseries Mapping:
ECHO | VAHydro
--- | ---
DMRValueNmbr | tsvlaue
MonitoringPeriodEndDate - NmbrOfSubmission | tstime (the first of the month X number of months before MonitoringPeriodEndDate)
MonitoringPeriodEndDate | tsendtime

### NmbrOfSubmission:
Number of Months | Reporting Frequency
--- | ---
1 | monthly
2 | bi-monthly
3 | quarterly
4 | triannual
6 | semi-annual
12 | annual

### Variable Definitions (proposed)
varkey | vardesc | uses (prop or ts)
--- | ---  | ---  
dmr_flag_units| Suspected unit converson, flagged when ECHO > 10.0 * VPDES Limit or 100 * Median| timeseries

![image](https://user-images.githubusercontent.com/4571170/42531183-55b349f2-8451-11e8-89d1-00d9fcbe3386.png)

**Comment by rburghol** [comment]
Moved to wiki.
